import type { SharedQuote } from '@/lib/share';
import { formatAud, formatDate } from '@/lib/quote';

export function QuoteDocument({ quote }: { quote: SharedQuote }) {
  const scope = quote.job.jobDescription || quote.job.scope || 'Electrical installation, testing and related services.';
  const costLines = [['Labour', quote.costs.labour], ['Materials', quote.costs.materials], ['Subcontractors', quote.costs.subcontractors], ['Other costs', quote.costs.otherCosts], [`Margin (${quote.costs.marginPercent}%)`, quote.totals.marginAmount]].filter(([, amount]) => Number(amount) > 0) as [string, number][];
  return <article id="quote-document" className="mx-auto w-full max-w-[794px] overflow-hidden bg-white text-slate-800 shadow-lg print:max-w-none print:shadow-none">
    <header className="border-b-4 border-slate-800 px-5 py-5 sm:px-8 sm:py-7"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-700 text-xl font-bold text-white">ϟ</div><div className="min-w-0"><p className="truncate text-lg font-bold">{quote.business.businessName || 'SparkQuote'}</p><p className="text-xs text-slate-500">Electrical Quote</p></div></div><div className="shrink-0 text-right"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Quote</p><p className="mt-1 max-w-[9rem] truncate text-base font-bold sm:text-xl">#{quote.quoteNumber}</p></div></div></header>
    <section className="grid grid-cols-1 gap-6 px-5 py-6 sm:grid-cols-2 sm:px-8"><ContactBlock title="From" rows={[quote.business.businessName, quote.business.businessAddress, quote.business.abn ? `ABN: ${quote.business.abn}` : '', quote.business.businessPhone, quote.business.businessEmail]} /><ContactBlock title="Prepared for" rows={[quote.customer.customerName, quote.customer.jobAddress, quote.customer.customerPhone, quote.customer.customerEmail]} /></section>
    <section className="mx-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:mx-8 sm:grid-cols-4"><Meta label="Quote number" value={`#${quote.quoteNumber}`} /><Meta label="Issued" value={formatDate(quote.issuedAt)} /><Meta label="Valid until" value={formatDate(quote.validUntil)} /><Meta label="Status" value="QUOTE" /></section>
    <section className="px-5 pt-7 sm:px-8"><Label>Scope of work</Label><p className="whitespace-pre-line rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-700">{scope}</p></section>
    <section className="px-5 py-7 sm:px-8"><Label>Quote breakdown</Label><div className="overflow-hidden rounded-lg border border-slate-200"><div className="hidden grid-cols-[1fr_auto] gap-4 bg-slate-800 px-4 py-3 text-xs font-bold uppercase tracking-wider text-white sm:grid"><span>Description</span><span>Amount</span></div>{costLines.length ? costLines.map(([label, amount]) => <CostLine key={label} label={label} amount={amount} />) : <div className="p-4 text-sm text-slate-500">No cost items have been added yet.</div>}</div></section>
    <section className="px-5 sm:px-8"><div className="ml-auto w-full max-w-sm"><Summary label="Cost subtotal" value={quote.totals.costSubtotal} /><Summary label="Subtotal (ex. GST)" value={quote.totals.netTotal} /><Summary label={`GST (${quote.costs.gstRate}%)`} value={quote.totals.gstAmount} /><div className="mt-2 flex justify-between rounded-lg bg-slate-800 px-4 py-3 text-white"><span className="font-bold uppercase tracking-wide text-sm">Total (incl. GST)</span><span className="text-lg font-bold">{formatAud(quote.totals.total)}</span></div></div></section>
    <section className="mt-8 border-t border-slate-200 px-5 py-6 sm:px-8"><Label>Terms & conditions</Label><p className="whitespace-pre-line text-xs leading-5 text-slate-600">{quote.business.termsAndConditions || 'This quote is valid for the period shown above.'}</p></section><footer className="border-t border-slate-200 px-5 py-5 text-center text-xs text-slate-400">Generated with SparkQuote</footer>
  </article>;
}
function ContactBlock({ title, rows }: { title: string; rows: string[] }) { return <div><Label>{title}</Label><div className="space-y-1 text-sm text-slate-600">{rows.filter(Boolean).map((row, index) => <p key={index} className={index === 0 ? 'font-bold text-slate-900' : ''}>{row}</p>)}</div></div>; }
function Label({ children }: { children: React.ReactNode }) { return <h2 className="mb-3 text-[11px] font-bold uppercase tracking-[.15em] text-slate-500">{children}</h2>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-words font-semibold text-slate-800">{value}</p></div>; }
function CostLine({ label, amount }: { label: string; amount: number }) { return <div className="grid grid-cols-[1fr_auto] gap-4 border-t border-slate-200 px-4 py-3 text-sm"><span className="font-medium text-slate-800">{label}</span><span className="font-semibold text-slate-800">{formatAud(amount)}</span></div>; }
function Summary({ label, value }: { label: string; value: number }) { return <div className="flex justify-between border-b border-slate-200 py-2 text-sm"><span className="text-slate-600">{label}</span><span className="font-semibold text-slate-800">{formatAud(value)}</span></div>; }
